[package]
name = "teo-runtime"
version = "0.0.58-alpha.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teo-parser = { path = "../teo-parser" }
teo-teon = { path = "../teo-teon" }
maplit = "1.0.2"