[package]
name = "teo-runtime"
version = "0.0.58-alpha.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teo-parser = { path = "../teo-parser" }
teo-teon = { path = "../teo-teon" }
maplit = "1.0.2"
indexmap = { version = "2.0.2", features = ["serde"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
educe = "0.4.23"
key-path = "0.1.11"